namespace: citizennone
name: debian_hardening_lite
version: 1.0.0
readme: README.md
authors:
  - Marcin Dołęgowski <marcin.dolegowski@debian.org.pl>
description: >
  Lightweight security hardening role for Debian-based systems. Includes tools like rkhunter, unattended-upgrades,
  basic SSH and sudo lockdown, log hygiene, and minimal service exposure. Ideal for minimal servers, labs, and DevOps environments.
license: MIT
min_ansible_version: "2.9"
platforms:
  - name: Debian
    versions:
      - bookworm
      - bullseye
      - buster
tags:
  - debian
  - security
  - hardening
  - ssh
  - sudo
  - monitoring
  - system
dependencies: []
