- name: Apt update
  ansible.builtin.apt:
    update_cache: true

- name: Install fail2ban package
  ansible.builtin.apt:
    name:
      - fail2ban
    state: present

- name: Copy fail2ban conf files
  when: ansible_distribution == 'Debian'
  ansible.builtin.copy:
    src: "fail2ban/{{ item }}"
    dest: "/etc/fail2ban/jail.d/{{ item }}"
    mode: '0644'
  loop: "{{ fail2ban_configs }}"

- name: Copy fail2ban template
  when: ansible_distribution == 'Debian'
  ansible.builtin.template:
    src: "fail2ban/{{ item }}"
    dest: "/etc/fail2ban/jail.d/{{ item }}"
    mode: '0644'
  loop: "{{ fail2ban_templates }}"
