- name: Check logrotate related installed packages
  ansible.builtin.include_tasks: installed-packages-check.yml
  when: logrotate_enabled | default(false)

- name: Deploy logrotate config for all enabled services
  ansible.builtin.template:
    src: "logrotate/{{ item.template }}"
    dest: "/etc/logrotate.d/{{ item.name }}"
    mode: '0644'
  loop: "{{ logrotate_services }}"
  when: item.enabled or (installed_packages is defined and item.name in installed_packages.stdout_lines)
