- name: Configure {{ ssh_admin_user }}
  ansible.builtin.include_tasks: configure-admin-user.yml
  when: ssh_enabled | default(false)

- name: Enable banner
  ansible.builtin.include_tasks: figlet-banner.yml
  when: ssh_enabled | default(false)
