- name: Backup sshd_conf
  ansible.builtin.command: cp /etc/ssh/sshd_config /etc/ssh/sshd_config.bck
  changed_when: true

- name: Set crontab to restore file in 30 minutes
  ansible.builtin.copy:
    src: ssh_hardening/ssh_restore_cron
    dest: /etc/cron.d/ssh_restore
    owner: root
    group: root
    mode: '0644'

- name: Display message for sshd restore
  ansible.builtin.debug:
    msg: "NOTE!!! SSH ROLLBACK HAS BEEN SET UP. TEST YOUR SSH CONNECTION AND REMOVE /etc/cron.d/ssh_restore FILE IF ALL IS OK"

- name: Configure sshd_conf file
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
    backrefs: true
  loop: "{{ sshd_entries }}"
  notify:
    - Restart ssh
