- name: Create sysctl hardening file
  ansible.builtin.file:
    path: /etc/sysctl.d/99-sysctl-hardening.conf
    owner: root
    group: root
    mode: '0644'
    state: touch
  when: sysctl_enabled

- name: Setup sysctl hardening
  ansible.builtin.lineinfile:
    path: /etc/sysctl.d/99-sysctl-hardening.conf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  loop: "{{ sysctl_entries }}"
  notify:
    - Restart sysctl
  when: sysctl_enabled
