- name: Restart ssh (systemd)
  ansible.builtin.service:
    name: ssh
    state: restarted
  when: ssh_systemd_restart and ssh_enabled
  changed_when: true

- name: Restart ssh (command)
  ansible.builtin.command:
    cmd: pkill sshd && /usr/sbin/sshd
  when: ssh_command_restart and ssh_enabled
  changed_when: true

- name: Restart ssh (init)
  ansible.builtin.command:
    cmd: /etc/init.d/ssh restart
  when: ssh_init_restart and ssh_enabled
  changed_when: true

- name: Restart sysctl
  ansible.builtin.command: sysctl --system
  register: sysctl_reload
  when: sysctl_enabled
  changed_when: "'error' not in sysctl_reload.stderr"
