driver:
  name: docker

platforms:
  - name: instance
    build_image: true
    dockerfile: Dockerfile
    image: debian_python_molecule
    privileged: true
    tty: true
    published_ports:
      - "2222:22"

provisioner:
  name: ansible
  lint: |
    ansible-lint
  inventory:
    links:
      group_vars: ../../group_vars/
      host_vars: ../../host_vars/
  env:
    ANSIBLE_ROLES_PATH: ../../..
